from matrix import Matrix

def menu():
    print('0) Exit \n 1) Create matrices\n 2) Add matrices \n 3) Multiply a matrix with an escalar \n 4) Multiply matrices \n 5) Transpose matrix \n 6) Matrix determinant \n 7) Adjugate matrix \n 8) Inverted matrix')
    while True: 
        inp = input('Choose one: ')
        if inp == '0':
            exit()
        elif inp == '1':
            m1 = Matrix()
            n = int(input('Enter the number of rows: '))
            m = int(input('Enter the number of columns: '))
            print('Enter the values of the matrix m1: ')
            m1.input_matrix(n,m)
            m1.clear()
            menu()
        elif inp == '2':
            m1 = Matrix()
            n = int(input('Enter the number of rows: '))
            m = int(input('Enter the number of columns: '))
            print('Enter the values of the matrix m1: ')
            m1.input_matrix(n,m)
            print()
            m2 = Matrix()
            print('Enter the values of the matrix m2: ')
            m2.input_matrix(n,m)  
            print('The sum between m1 and m2 is: ')
            m1 + m2 
            m1.clear()
            m2.clear()
            menu()
        elif inp == '3':
            m3 = Matrix()
            n3 = int(input('Enter the number of rows: '))
            k3 = int(input('Enter the number of columns: '))
            print('Enter the values of the matrix m1: ')
            m3.input_matrix(n3,k3)
            number = int(input('Enter the scalar: '))
            for e in m3.scalar_product(number): 
                print(e)
            m3.clear()
            menu()
        elif inp == '4':
            m1 = Matrix()
            n = int(input('Enter the number of rows for matrix 1: '))
            m = int(input('Enter the number of columns for matrix 1: '))
            print('Enter the values of the matrix m1: ')
            m1.input_matrix(n,m)
            print()
            m2 = Matrix()
            n2 = int(input('Enter the number of rows for matrix 2: '))
            m2 = int(input('Enter the number of columns for matrix 2: '))
            print('Enter the values of the matrix m2: ')
            m2.input_matrix(n2,m2)
            print('The product between m1 and m2 is: ')
            m1.product(m2)
            m1.clear()
            m2.clear()
            menu()
        elif inp == '5': 
            m1 = Matrix()
            n = int(input('Enter the number of rows: '))
            m = int(input('Enter the number of columns: '))
            print('Enter the values of the matrix m1: ')
            m1.input_matrix(n,m)
            print("The transpose is: ")
            m1.transpose()            
        elif inp == '6': 
            m1 = Matrix()
            n = int(input('Enter the number of rows: '))
            m = int(input('Enter the number of columns: '))
            print('Enter the values of the matrix m1: ')
            m1.input_matrix(n,m)
            print("The determinant is: ")  
            m1.determinant_matrix(m1.matrix)          
            m1.clear()
            menu()
        elif inp == '7':
            m1 = Matrix()
            n = int(input('Enter the number of rows: '))
            m = int(input('Enter the number of columns: '))
            print('Enter the values of the matrix m1: ')
            m1.input_matrix(n,m)
            print("The adjugate matrix is: ")  
            m1.adjugate_matrix(m1.matrix)          
            m1.clear()
            menu()
        elif inp == '8':
            m1 = Matrix()
            n = int(input('Enter the number of rows: '))
            m = int(input('Enter the number of columns: '))
            print('Enter the values of the matrix m1: ')
            m1.input_matrix(n,m)
            print("The inverted matrix is: ")  
            for e in m1.inverted_matrix(m1.matrix):
                print(e)          
            m1.clear()
            menu()

menu()

